import { InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { Endpoint, Paths } from '@/common/Label'
import { client } from '@/libs/client'
import { Blog, category } from '@/types/blog'

export const getStaticProps = async () => {
  const blog = await client.get({ endpoint: `${Endpoint.blog}` })
  const category = await client.get({ endpoint: `${Endpoint.categories}` })

  return {
    props: {
      blogs: blog.contents,
      categories: category.contents,
    },
  }
}

type Props = {
  blogs: Blog[]
  categories: category[]
}

const Home: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  blogs,
  categories,
}: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {blogs.length > 0 && (
          <ul>
            {blogs.map((blog: any) => (
              <li key={blog.id}>
                <Link href={`${Paths.blog}/${blog.id}`}>
                  <h2>{blog.title}</h2>
                  {blog.eyecatch.url && (
                    <img src={blog.eyecatch.url} alt={`${blog.title}のアイキャッチ画像`} />
                  )}
                </Link>
              </li>
            ))}
          </ul>
        )}
      </main>
    </>
  )
}

export default Home
